//
//  ModelController.swift
//  IndustrialKit
//
//  Created by Artem on 11.11.2022.
//

import Foundation
import RealityKit

/// A controller that manages the visual model of a workspace object.
///
/// `ModelController` provides an abstraction layer for interacting with
/// the visual representation of a production object within a scene.
///
/// The controller operates on a connected hierarchy of entities and enables:
/// - Transform updates (position, rotation)
/// - Animation application
/// - Dynamic visual adjustments based on object parameters
///
/// The controller does not construct the visual model. Instead, it attaches
/// to an existing entity hierarchy and manipulates it according to the
/// logical state of the associated workspace object.
///
/// Subclasses implement domain-specific behavior for robots, tools,
/// and other controllable production elements.
///
open class ModelController
{
    required public init() {}
    
    /// Creates a copy of the model controller.
    ///
    /// Subclasses should override this method if additional state
    /// needs to be preserved during copying.
    ///
    /// - Returns: A new instance of the same controller type.
    open func copy() -> Self
    {
        return type(of: self).init()
    }
    
    // MARK: - Reality Functions
    /// A dictionary of connected entities indexed by their names.
    ///
    /// The dictionary stores references to specific entities within the
    /// visual model, allowing direct access for updates and animations.
    public var entities = [String: Entity]()

    /// A list of entity names used to establish connections.
    ///
    /// Subclasses override this property to define which entities
    /// should be extracted from the model hierarchy.
    open var entity_names: [String]
    {
        return [String]()
    }

    /// Connects entities from the provided root entity.
    ///
    /// The method searches for entities with names defined in ``entity_names``
    /// and stores references to them in the ``entities`` dictionary.
    ///
    /// - Parameter entity: A root entity of the workspace object model.
    open func connect_entities(of entity: Entity)
    {
        entities.removeAll()
        
        for entity_name in entity_names
        {
            if let found_entity = entity.child_entity(withName: entity_name, recursively: true)
            {
                entities[entity_name] = found_entity
            }
        }
    }
    
    /// Disconnects all previously connected entities.
    ///
    /// This method clears the internal entity dictionary,
    /// removing all references to the visual model.
    open func disconnect_entities()
    {
        entities.removeAll()
    }
    
    /// Initial transform states for connected entities.
    ///
    /// Subclasses can override this property to provide a baseline set
    /// of transforms used for resetting or initializing the visual model.
    open var inital_entities_transform: [EntityAnimationData]
    {
        return []
    }
    
    // MARK: - Device State Data
    /// Current output data generated by the controller.
    ///
    /// The controller produces ``DeviceOutputData`` reflecting the current
    /// state of the visual model or associated device.
    ///
    /// Subclasses override this property to provide meaningful state data
    /// for visualization and monitoring.
    open var current_device_output: DeviceOutputData?
    {
        // Prepare controller output
        return DeviceOutputData()
    }
    
    /// Initial output data used to reset controller state.
    ///
    /// This value represents a baseline dataset that can be used to
    /// initialize or restore the device output to its default state.
    ///
    /// Subclasses override this property to define initial charts
    /// and state items.
    open var initial_device_output: DeviceOutputData?
    {
        // Reset contoller output
        return nil
    }
}
